name: Build Superset Image

on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Show files in repo
        run: |
          pwd
          ls -la
          echo "----- Dockerfile -----"
          cat Dockerfile

      - name: Build Docker image
        run: docker build --no-cache --progress=plain -t superset-custom .

      - name: Test Python dependencies inside image
        run: |
          docker run --rm superset-custom:latest /app/.venv/bin/python -c "import psycopg2, pyodbc, pymysql, pandas, openpyxl; print('Python dependencies OK')"

      - name: Save Docker image
        run: docker save superset-custom > superset.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v5
        with:
          name: superset-image
          path: superset.tar
